<Project>
  <PropertyGroup>
    <ProductVersion>1.0.0.91</ProductVersion>
    <Version>$(ProductVersion)</Version>
    <AssemblyVersion>$(ProductVersion)</AssemblyVersion>
    <FileVersion>$(ProductVersion)</FileVersion>
    <InformationalVersion>$(ProductVersion)</InformationalVersion>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
    <Deterministic>true</Deterministic>
  </PropertyGroup>
</Project>
