// <auto-generated />
using System;
using Office = Microsoft.Office.Core;

namespace ChuanHoa.AddIn.Vsto.Ribbon
{
    public sealed partial class ChuanHoaRibbon
    {
        public void RibbonOnLoad(Office.IRibbonUI ribbonUi)
        {
            if (ribbonUi == null)
            {
                return;
            }

            CompleteRibbonLoad(ribbonUi);
        }
        public bool GetEnabledAutoFixAll2026(Office.IRibbonControl control)
        {
            return Runtime.IsEnabled(RequireControlId(control));
        }
        public bool GetEnabledChuyenDoiUnicode(Office.IRibbonControl control)
        {
            return Runtime.IsEnabled(RequireControlId(control));
        }
        public bool GetEnabledCoChu13(Office.IRibbonControl control)
        {
            return Runtime.IsEnabled(RequireControlId(control));
        }
        public bool GetEnabledCoChu14(Office.IRibbonControl control)
        {
            return Runtime.IsEnabled(RequireControlId(control));
        }
        public bool GetEnabledCoChu15(Office.IRibbonControl control)
        {
            return Runtime.IsEnabled(RequireControlId(control));
        }
        public bool GetEnabledHasDocument(Office.IRibbonControl control)
        {
            return Runtime.IsEnabled(RequireControlId(control));
        }
        public bool GetEnabledHienThi(Office.IRibbonControl control)
        {
            return Runtime.IsEnabled(RequireControlId(control));
        }
        public bool GetEnabledKiemTra(Office.IRibbonControl control)
        {
            return Runtime.IsEnabled(RequireControlId(control));
        }
        public bool GetEnabledLoaiVanBan(Office.IRibbonControl control)
        {
            return Runtime.IsEnabled(RequireControlId(control));
        }
        public int GetItemCountLoaiVanBan(Office.IRibbonControl control)
        {
            return Runtime.GetItemCount(RequireControlId(control));
        }
        public string GetItemLabelLoaiVanBan(Office.IRibbonControl control, int index)
        {
            return Runtime.GetItemLabel(RequireControlId(control), index);
        }
        public bool GetPressedDauGoc(Office.IRibbonControl control)
        {
            return Runtime.GetPressed(RequireControlId(control));
        }
        public bool GetPressedKyHieuSoanThao(Office.IRibbonControl control)
        {
            return Runtime.GetPressed(RequireControlId(control));
        }
        public bool GetPressedRanhGioiVanBan(Office.IRibbonControl control)
        {
            return Runtime.GetPressed(RequireControlId(control));
        }
        public int GetSelectedIndexLoaiVanBan(Office.IRibbonControl control)
        {
            return Runtime.GetSelectedItemIndex(RequireControlId(control));
        }
        public int GetSelectedIndexQuyDinh(Office.IRibbonControl control)
        {
            return Runtime.GetSelectedItemIndex(RequireControlId(control));
        }
        public void OnAutoFixAll2026(Office.IRibbonControl control)
        {
            Runtime.ExecuteButton(RequireControlId(control));
        }
        public void OnCanDinhO(Office.IRibbonControl control)
        {
            Runtime.ExecuteButton(RequireControlId(control));
        }
        public void OnCanGiuaO(Office.IRibbonControl control)
        {
            Runtime.ExecuteButton(RequireControlId(control));
        }
        public void OnChenQrCode(Office.IRibbonControl control)
        {
            Runtime.ExecuteButton(RequireControlId(control));
        }
        public void OnChenSoTrang(Office.IRibbonControl control)
        {
            Runtime.ExecuteButton(RequireControlId(control));
        }
        public void OnChenTrangDoc(Office.IRibbonControl control)
        {
            Runtime.ExecuteButton(RequireControlId(control));
        }
        public void OnChenTrangNgang(Office.IRibbonControl control)
        {
            Runtime.ExecuteButton(RequireControlId(control));
        }
        public void OnChonLoaiVanBan(Office.IRibbonControl control, string selectedId, int selectedIndex)
        {
            Runtime.SelectDropDownItem(RequireControlId(control), selectedId, selectedIndex);
        }
        public void OnChonQuyDinh(Office.IRibbonControl control, string selectedId, int selectedIndex)
        {
            Runtime.SelectDropDownItem(RequireControlId(control), selectedId, selectedIndex);
        }
        public void OnChuanHoaAnh(Office.IRibbonControl control)
        {
            Runtime.ExecuteButton(RequireControlId(control));
        }
        public void OnChuanHoaBang(Office.IRibbonControl control)
        {
            Runtime.ExecuteButton(RequireControlId(control));
        }
        public void OnChuyenDoiUnicode(Office.IRibbonControl control)
        {
            Runtime.ExecuteButton(RequireControlId(control));
        }
        public void OnCoChu(Office.IRibbonControl control)
        {
            Runtime.ExecuteButton(RequireControlId(control));
        }
        public void OnCoChu13(Office.IRibbonControl control)
        {
            Runtime.ExecuteButton(RequireControlId(control));
        }
        public void OnCoChu14(Office.IRibbonControl control)
        {
            Runtime.ExecuteButton(RequireControlId(control));
        }
        public void OnCoChu15(Office.IRibbonControl control)
        {
            Runtime.ExecuteButton(RequireControlId(control));
        }
        public void OnDauGoc(Office.IRibbonControl control, bool pressed)
        {
            Runtime.SetPressed(RequireControlId(control), pressed);
        }
        public void OnDinhDangTrangGiay(Office.IRibbonControl control)
        {
            Runtime.ExecuteButton(RequireControlId(control));
        }
        public void OnDoiDauThapPhan(Office.IRibbonControl control)
        {
            Runtime.ExecuteButton(RequireControlId(control));
        }
        public void OnDungBoStyle13(Office.IRibbonControl control)
        {
            Runtime.ExecuteButton(RequireControlId(control));
        }
        public void OnDungBoStyle14(Office.IRibbonControl control)
        {
            Runtime.ExecuteButton(RequireControlId(control));
        }
        public void OnDungBoStyle15(Office.IRibbonControl control)
        {
            Runtime.ExecuteButton(RequireControlId(control));
        }
        public void OnGianChuNormal(Office.IRibbonControl control)
        {
            Runtime.ExecuteButton(RequireControlId(control));
        }
        public void OnGianChuRa(Office.IRibbonControl control)
        {
            Runtime.ExecuteButton(RequireControlId(control));
        }
        public void OnGioiThieu(Office.IRibbonControl control)
        {
            Runtime.ExecuteButton(RequireControlId(control));
        }
        public void OnGuiPhanHoi(Office.IRibbonControl control)
        {
            Runtime.ExecuteButton(RequireControlId(control));
        }
        public void OnKeepWithNext(Office.IRibbonControl control)
        {
            Runtime.ExecuteButton(RequireControlId(control));
        }
        public void OnKiemTra(Office.IRibbonControl control)
        {
            Runtime.ExecuteButton(RequireControlId(control));
        }
        public void OnKiemTraChinhTa(Office.IRibbonControl control)
        {
            Runtime.ExecuteButton(RequireControlId(control));
        }
        public void OnKiemTraPhienBanMoi(Office.IRibbonControl control)
        {
            Runtime.ExecuteButton(RequireControlId(control));
        }
        public void OnKieuOaUy(Office.IRibbonControl control)
        {
            Runtime.ExecuteButton(RequireControlId(control));
        }
        public void OnKieuOaUy2(Office.IRibbonControl control)
        {
            Runtime.ExecuteButton(RequireControlId(control));
        }
        public void OnKyHieuSoanThao(Office.IRibbonControl control, bool pressed)
        {
            Runtime.SetPressed(RequireControlId(control), pressed);
        }
        public void OnLapDongTieuDe(Office.IRibbonControl control)
        {
            Runtime.ExecuteButton(RequireControlId(control));
        }
        public void OnRanhGioiVanBan(Office.IRibbonControl control, bool pressed)
        {
            Runtime.SetPressed(RequireControlId(control), pressed);
        }
        public void OnSuaLoiDangChon(Office.IRibbonControl control)
        {
            Runtime.ExecuteButton(RequireControlId(control));
        }
        public void OnXoaKyTuThuaBangExcel(Office.IRibbonControl control)
        {
            Runtime.ExecuteButton(RequireControlId(control));
        }
        public void OnXoaTrangThua(Office.IRibbonControl control)
        {
            Runtime.ExecuteButton(RequireControlId(control));
        }
    }
}
